//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresTanimlari
    {
        public int AdresTanimiID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string SehirAdi { get; set; }
        public string IlceAdi { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
    }
}
