//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnakartUrunler
    {
        public int AnakartUrunID { get; set; }
        public string AnakartAdi { get; set; }
        public string Marka { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<int> Stok { get; set; }
        public string Uyumluluk { get; set; }
        public string Yapi { get; set; }
        public string IslemciSoketTipi { get; set; }
        public string RamTipi { get; set; }
        public string MbChipseti { get; set; }
        public string MbRamSlotSayisi { get; set; }
        public string SpdifCikisi { get; set; }
        public string Ps2 { get; set; }
        public string Sekizkanal { get; set; }
        public string Ethernet { get; set; }
        public string KablosuzWifi { get; set; }
        public string usb2 { get; set; }
        public string usb3 { get; set; }
        public string ClearCmosButon { get; set; }
        public string SupremeFX { get; set; }
        public string Bluetooth { get; set; }
        public string Ses { get; set; }
        public string PciExpress { get; set; }
        public string Sata3 { get; set; }
        public string SataExpress { get; set; }
        public string M2Sata { get; set; }
        public string CoreI7 { get; set; }
        public string Mensei { get; set; }
        public string Garanti { get; set; }
        public string resim1 { get; set; }
        public string resim2 { get; set; }
        public string resim3 { get; set; }
        public string resim4 { get; set; }
    }
}
