//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkranKartiUrunler
    {
        public int EkranKartiUrunID { get; set; }
        public string EkranKartiAdi { get; set; }
        public string Marka { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<int> Stok { get; set; }
        public string CekirdekHizi { get; set; }
        public string RamKapasitesi { get; set; }
        public string BellekHizi { get; set; }
        public string GrafikChipsetiMarkasi { get; set; }
        public string EkranKartiChipseti { get; set; }
        public string BellekTipi { get; set; }
        public string BellekArayuzu { get; set; }
        public string PciExpress3 { get; set; }
        public string DisplayPort { get; set; }
        public string HdcpDestegi { get; set; }
        public string Dvi { get; set; }
        public string Hdmi { get; set; }
        public string GucTuketimi { get; set; }
        public string Mensei { get; set; }
        public string Garanti { get; set; }
        public string Cozunurluk { get; set; }
        public string resim1 { get; set; }
        public string resim2 { get; set; }
        public string resim3 { get; set; }
    }
}
