//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTicaretEntities : DbContext
    {
        public eTicaretEntities()
            : base("name=eTicaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdresTanimlari> AdresTanimlari { get; set; }
        public virtual DbSet<AnakartUrunler> AnakartUrunler { get; set; }
        public virtual DbSet<EkranKartiUrunler> EkranKartiUrunler { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<IslemciUrunler> IslemciUrunler { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<Adminler> Adminler { get; set; }
    }
}
