//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int FaturaID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string UyeAdi { get; set; }
        public string UyeSoyad { get; set; }
        public string UyeAdres { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string UrunAdlari { get; set; }
        public string UrunFiyatlari { get; set; }
        public string UrunAdetleri { get; set; }
        public Nullable<double> ToplamFiyat { get; set; }
    }
}
