//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemciUrunler
    {
        public int IslemciUrunID { get; set; }
        public string IslemciAdi { get; set; }
        public string Marka { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<int> Stok { get; set; }
        public string IslemciSoketTipi { get; set; }
        public string IslemciNumarasi { get; set; }
        public string IslemciTeknolojisi { get; set; }
        public string IslemciHizi { get; set; }
        public string IslemciOnBellek { get; set; }
        public string Mensei { get; set; }
        public string Garanti { get; set; }
        public string KutuluKutusuz { get; set; }
        public string resim1 { get; set; }
    }
}
