//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string TurID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string UrunResim { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> UrunFiyat { get; set; }
    }
}
