//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int UyeID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Sifre { get; set; }
        public string SifreTekrar { get; set; }
        public string DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string GizliSoru { get; set; }
        public string GizliSoruCevap { get; set; }
        public string UyeFoto { get; set; }
    }
}
