//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknomar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teknomar.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string Adiniz {
            get {
                return ResourceManager.GetString("Adiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anakart.
        /// </summary>
        public static string Anakart {
            get {
                return ResourceManager.GetString("Anakart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anakartlar.
        /// </summary>
        public static string Anakartlar {
            get {
                return ResourceManager.GetString("Anakartlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellek(RAM).
        /// </summary>
        public static string Bellek {
            get {
                return ResourceManager.GetString("Bellek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellek Özellikleri.
        /// </summary>
        public static string BellekOzellikleri {
            get {
                return ResourceManager.GetString("BellekOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellek Tipi.
        /// </summary>
        public static string BellekTipi {
            get {
                return ResourceManager.GetString("BellekTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizi daha iyi tanıyabilmemiz ve size özel kampanya oluşturabilmemiz için aşağıdaki alanları doldurarak TEKNOMAR&apos;a üye olabilirsiniz..
        /// </summary>
        public static string Bilgilendirme {
            get {
                return ResourceManager.GetString("Bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string CikisYap {
            get {
                return ResourceManager.GetString("CikisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string Cinsiyet {
            get {
                return ResourceManager.GetString("Cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Çok Özellik.
        /// </summary>
        public static string DahaCokOzellik {
            get {
                return ResourceManager.GetString("DahaCokOzellik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekran Kartı.
        /// </summary>
        public static string EkranKarti {
            get {
                return ResourceManager.GetString("EkranKarti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adresiniz.
        /// </summary>
        public static string EmailAdresiniz {
            get {
                return ResourceManager.GetString("EmailAdresiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        public static string Erkek {
            get {
                return ResourceManager.GetString("Erkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garanti.
        /// </summary>
        public static string Garanti {
            get {
                return ResourceManager.GetString("Garanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Özellikler.
        /// </summary>
        public static string GenelOzellikler {
            get {
                return ResourceManager.GetString("GenelOzellikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ YAP.
        /// </summary>
        public static string GirisYap {
            get {
                return ResourceManager.GetString("GirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikamız.
        /// </summary>
        public static string GizlilikPolitikamiz {
            get {
                return ResourceManager.GetString("GizlilikPolitikamiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizli Soru.
        /// </summary>
        public static string GizliSoru {
            get {
                return ResourceManager.GetString("GizliSoru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizli Sorunun Cevabını Giriniz.
        /// </summary>
        public static string GizliSoruCevap {
            get {
                return ResourceManager.GetString("GizliSoruCevap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güç Kaynağı.
        /// </summary>
        public static string GucKaynagi {
            get {
                return ResourceManager.GetString("GucKaynagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Gün İçinde İade.
        /// </summary>
        public static string GunIcindeIade {
            get {
                return ResourceManager.GetString("GunIcindeIade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEKNOMAR dan Almış Olduğunuz ve Hiç Kullanmadığınız Ürünleri 15 Gün İçerisinde İade Edebilir veya Değiştirebilirsiniz..
        /// </summary>
        public static string GunIcindeIade2 {
            get {
                return ResourceManager.GetString("GunIcindeIade2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harici Disk.
        /// </summary>
        public static string HariciDisk {
            get {
                return ResourceManager.GetString("HariciDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string Hosgeldiniz {
            get {
                return ResourceManager.GetString("Hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk arabanızın markası nedir?.
        /// </summary>
        public static string IlkAraba {
            get {
                return ResourceManager.GetString("IlkAraba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk okulunuzun adı nedir?.
        /// </summary>
        public static string IlkOkul {
            get {
                return ResourceManager.GetString("IlkOkul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        public static string InsanKaynaklari {
            get {
                return ResourceManager.GetString("InsanKaynaklari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemci.
        /// </summary>
        public static string Islemci {
            get {
                return ResourceManager.GetString("Islemci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemci Özellikleri.
        /// </summary>
        public static string IslemciOzellikleri {
            get {
                return ResourceManager.GetString("IslemciOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemci Soket Tipi.
        /// </summary>
        public static string IslemciSoketTipi {
            get {
                return ResourceManager.GetString("IslemciSoketTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Rehberi.
        /// </summary>
        public static string IslemRehberi {
            get {
                return ResourceManager.GetString("IslemRehberi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        public static string Kadin {
            get {
                return ResourceManager.GetString("Kadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapıda Nakit Ödeme.
        /// </summary>
        public static string KapidaNakitOdeme {
            get {
                return ResourceManager.GetString("KapidaNakitOdeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternetten alışveriş TEKNOMAR ile çok kolay..
        /// </summary>
        public static string KapidaNakitOdeme2 {
            get {
                return ResourceManager.GetString("KapidaNakitOdeme2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Bedava.
        /// </summary>
        public static string KargoBedava {
            get {
                return ResourceManager.GetString("KargoBedava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEKNOMAR dan yapacağınız alışverişlerinizde KARGO BEDAVA.
        /// </summary>
        public static string KargoBedava2 {
            get {
                return ResourceManager.GetString("KargoBedava2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasa.
        /// </summary>
        public static string Kasa {
            get {
                return ResourceManager.GetString("Kasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyifli Garanti.
        /// </summary>
        public static string KeyifliGaranti {
            get {
                return ResourceManager.GetString("KeyifliGaranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string Kurumsal {
            get {
                return ResourceManager.GetString("Kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Haritası.
        /// </summary>
        public static string MarkaHaritasi {
            get {
                return ResourceManager.GetString("MarkaHaritasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB Bellek Slot Sayisi.
        /// </summary>
        public static string MBBellekSlotSayisi {
            get {
                return ResourceManager.GetString("MBBellekSlotSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB Çip Seti.
        /// </summary>
        public static string MBCipSeti {
            get {
                return ResourceManager.GetString("MBCipSeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menşei.
        /// </summary>
        public static string Mensei {
            get {
                return ResourceManager.GetString("Mensei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitör.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Hizmetleri.
        /// </summary>
        public static string MusteriHizmetleri {
            get {
                return ResourceManager.GetString("MusteriHizmetleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Seçenekleri.
        /// </summary>
        public static string OdemeSecenekleri {
            get {
                return ResourceManager.GetString("OdemeSecenekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabit Disk.
        /// </summary>
        public static string SabitDisk {
            get {
                return ResourceManager.GetString("SabitDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPETE EKLE.
        /// </summary>
        public static string SepeteEkle {
            get {
                return ResourceManager.GetString("SepeteEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string Sepetim {
            get {
                return ResourceManager.GetString("Sepetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Takip Formu.
        /// </summary>
        public static string ServisTakipFormu {
            get {
                return ResourceManager.GetString("ServisTakipFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ses Kartı.
        /// </summary>
        public static string SesKarti {
            get {
                return ResourceManager.GetString("SesKarti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        public static string Sifreniz {
            get {
                return ResourceManager.GetString("Sifreniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string SifreTekrar {
            get {
                return ResourceManager.GetString("SifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Aşamaları.
        /// </summary>
        public static string SiparisAsamalari {
            get {
                return ResourceManager.GetString("SiparisAsamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Haritası.
        /// </summary>
        public static string SiteHaritasi {
            get {
                return ResourceManager.GetString("SiteHaritasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string Soyadiniz {
            get {
                return ResourceManager.GetString("Soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD.
        /// </summary>
        public static string Ssd {
            get {
                return ResourceManager.GetString("Ssd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.S.S.
        /// </summary>
        public static string sss {
            get {
                return ResourceManager.GetString("sss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok.
        /// </summary>
        public static string Stok {
            get {
                return ResourceManager.GetString("Stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Özellikler.
        /// </summary>
        public static string TeknikOzellikler {
            get {
                return ResourceManager.GetString("TeknikOzellikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numaranız.
        /// </summary>
        public static string TelefonNumaraniz {
            get {
                return ResourceManager.GetString("TelefonNumaraniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkiye’nin Teknoloji &amp; Bilgisayar Hiper Mağazası.
        /// </summary>
        public static string Turkiyenin {
            get {
                return ResourceManager.GetString("Turkiyenin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Kartı.
        /// </summary>
        public static string TvKarti {
            get {
                return ResourceManager.GetString("TvKarti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Özellikleri.
        /// </summary>
        public static string UrunOzellikleri {
            get {
                return ResourceManager.GetString("UrunOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü Gör.
        /// </summary>
        public static string UrunuGor {
            get {
                return ResourceManager.GetString("UrunuGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi.
        /// </summary>
        public static string UyeGirisi {
            get {
                return ResourceManager.GetString("UyeGirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik.
        /// </summary>
        public static string Uyelik {
            get {
                return ResourceManager.GetString("Uyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYE OL.
        /// </summary>
        public static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyumluluk.
        /// </summary>
        public static string Uyumluluk {
            get {
                return ResourceManager.GetString("Uyumluluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapı.
        /// </summary>
        public static string Yapi {
            get {
                return ResourceManager.GetString("Yapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üyelik.
        /// </summary>
        public static string YeniUyelik {
            get {
                return ResourceManager.GetString("YeniUyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Başlığı Giriniz.
        /// </summary>
        public static string YorumBasligiGiriniz {
            get {
                return ResourceManager.GetString("YorumBasligiGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Giriniz.
        /// </summary>
        public static string YorumGiriniz {
            get {
                return ResourceManager.GetString("YorumGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YORUM YAP.
        /// </summary>
        public static string YorumYap {
            get {
                return ResourceManager.GetString("YorumYap", resourceCulture);
            }
        }
    }
}
